version: "3.2"
services:
  webstack:
    restart: always
    container_name: webstack_backend
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./static:/app/api/static
    environment:
      - DB_NAME=webstack
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
    ports:
      - "8000:8000"

  frontend:
    restart: always
    command: serve -s build
    container_name: webstack_frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - webstack
