version: "3.2"
services:
  webstack:
    image: webstack:latest
    restart: always
    container_name: webstack
    volumes:
      - <website_dir>:/app/web/
    environment:
      - DB_NAME=webstack
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
    ports:
      - "8000:8000"
