# Generated by Django 3.2.5 on 2022-06-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('status', models.PositiveIntegerField(choices=[(0, 'Deleted'), (1, 'Normal')], default=1)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='分组名')),
                ('icon', models.CharField(default='linecons-star', max_length=255, verbose_name='分组图标')),
                ('weight', models.IntegerField(default=1, verbose_name='分组权重')),
            ],
            options={
                'verbose_name': '分组',
                'verbose_name_plural': '分组',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('status', models.PositiveIntegerField(choices=[(0, 'Deleted'), (1, 'Normal')], default=1)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='网站名称')),
                ('description', models.CharField(max_length=255, verbose_name='网站描述')),
                ('url', models.URLField(verbose_name='网站链接')),
                ('title', models.CharField(max_length=255, verbose_name='原始标题')),
                ('icon', models.URLField(default='https://aupicgo.oss-cn-shanghai.aliyuncs.com/img/20200910125957.ico', verbose_name='网站图标')),
                ('weight', models.IntegerField(default=1, verbose_name='网站权重')),
                ('menu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.menu')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
                'db_table': 'website',
            },
        ),
    ]
