# Generated by Django 3.2.5 on 2022-06-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Deleted'), (1, 'Normal')], default=1)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
            ],
            options={
                'verbose_name': '网络环境',
                'verbose_name_plural': '网络环境',
                'db_table': 'webstack_env',
            },
        ),
        migrations.CreateModel(
            name='SiteGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Deleted'), (1, 'Normal')], default=1)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('icon', models.CharField(default='linecons-star', max_length=255, verbose_name='图标')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
            ],
            options={
                'verbose_name': '网站分组',
                'verbose_name_plural': '网站分组',
                'db_table': 'webstack_site_group',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Deleted'), (1, 'Normal')], default=1)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('url', models.URLField(verbose_name='链接')),
                ('title', models.CharField(max_length=255, verbose_name='原始标题')),
                ('icon', models.URLField(default='https://aupicgo.oss-cn-shanghai.aliyuncs.com/img/20200910125957.ico', verbose_name='站点图标')),
                ('weight', models.IntegerField(default=1, verbose_name='网站权重')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.sitegroup')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
                'db_table': 'webstack_site',
            },
        ),
        migrations.CreateModel(
            name='EnvWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Deleted'), (1, 'Normal')], default=1)),
                ('url', models.URLField(verbose_name='链接')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.environment')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.site')),
            ],
            options={
                'verbose_name': '环境链接',
                'verbose_name_plural': '环境链接',
                'db_table': 'webstack_env_site',
            },
        ),
    ]
